# Конфигурация агента для мониторинга

agent:
  name: "my-monitoring-agent"  # Имя агента (уникальный идентификатор)
  interval: 60                 # Интервал сбора метрик (в секундах)
  log_level: "info"            # Уровень логирования (например, debug, info, warn, error)
  retry_count: 3               # Количество попыток при неудаче отправки метрик

server:
  address: "localhost"     # IP-адрес или доменное имя сервера для отправки метрик
  port: 8080                   # Порт для отправки метрик на сервер
  protocol: "http"             # Протокол для отправки данных (например, http, https)
  endpoint: "/metrics"         # Конечная точка на сервере для приема метрик

host:
  group: "production"          # Группа, к которой принадлежит хост (например, production, staging, development)
  tags:                        # Дополнительные теги для идентификации хоста
    - "linux"
    - "web-server"
    - "datacenter1"

security:
  auth_token: "your-secret-token"  # Токен авторизации для отправки метрик на сервер (если требуется)
  ssl_verify: true                 # Проверка SSL-сертификата при отправке данных (если используется HTTPS)

# Дополнительные параметры
advanced:
  timeout: 5                   # Таймаут для отправки данных на сервер (в секундах)
  max_queue_size: 100          # Максимальный размер очереди метрик, ожидающих отправки
