metrics:
  cpu: true                    # Включить/выключить сбор метрик CPU
  memory: true                 # Включить/выключить сбор метрик памяти
  disk: true                   # Включить/выключить сбор метрик дискового пространства
  network: true                # Включить/выключить сбор сетевых метрик